[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.ci]
fuzz = { runs = 10000 }

[dependencies]
"@openzeppelin-contracts" = { version = "5.3.0", git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v5.3.0" }
"@octant-core" = { version = "0.1.0", git = "https://github.com/golemfoundation/octant-v2-core", tag = "v0.1.0" }

[rpc_endpoints]
tenderly = "https://virtual.mainnet.eu.rpc.tenderly.co/418c4044-1824-4f17-88fd-3541421b25c6"
